# Generated by Django 4.2.21 on 2025-10-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=100)),
                ('DOI', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
