# Generated by Django 4.2.21 on 2025-10-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='authors',
        ),
    ]
