# Generated by Django 4.2.21 on 2025-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_author_remove_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Article_author',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
