# Generated by Django 4.2.21 on 2025-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_article_authors_delete_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
