# Generated by Django 4.2.21 on 2025-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_image1_article_image14_article_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary of the article', max_length=300),
        ),
    ]
