# Generated by Django 4.2.21 on 2025-10-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='image14',
            new_name='image4',
        ),
        migrations.AddField(
            model_name='article',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
